export const metadata = {
  title: 'd-DOT 2022 by MUICT',
  description: 'Generated by Next.js',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body>
      <header>
    <div id="header-text">
        <h1 id="header-text-char">d-DOT 2022 by MUICT</h1>
    </div>
</header>
        {children}
        <footer id="foot">
        <h6>d-DOT 2022 Web Appication</h6>
    </footer>
      </body>
    </html>
  )
}
