import "./login.css";

import Header from "./Header.jsx";

export const metadata = {
  title: 'd-DOT 2022 by MUICT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <><html lang="en">
        <body>
          <Header/>
          {children}
          <footer id="foot">
        <h6>d-DOT 2022 Web Application</h6>
    </footer>
        </body>
      </html></>
  )
}
